// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWt7cNdkBv_11sw0b_w4VOf5ZnZmqfwQE',
    appId: '1:391352734113:web:503e0b23943a544d257be0',
    messagingSenderId: '391352734113',
    projectId: 'eqlert-11976',
    authDomain: 'eqlert-11976.firebaseapp.com',
    storageBucket: 'eqlert-11976.appspot.com',
    measurementId: 'G-ZJC3KJF3Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLLUrX_6cNTf4zwz-Dtd-6ydzpPlomaiI',
    appId: '1:391352734113:android:449bf5326776696b257be0',
    messagingSenderId: '391352734113',
    projectId: 'eqlert-11976',
    storageBucket: 'eqlert-11976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8p7YeoKLUQxIdTM98gLEda3ouC20AoI8',
    appId: '1:391352734113:ios:c02898104f3ca061257be0',
    messagingSenderId: '391352734113',
    projectId: 'eqlert-11976',
    storageBucket: 'eqlert-11976.appspot.com',
    iosBundleId: 'com.example.eqlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8p7YeoKLUQxIdTM98gLEda3ouC20AoI8',
    appId: '1:391352734113:ios:c02898104f3ca061257be0',
    messagingSenderId: '391352734113',
    projectId: 'eqlert-11976',
    storageBucket: 'eqlert-11976.appspot.com',
    iosBundleId: 'com.example.eqlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWt7cNdkBv_11sw0b_w4VOf5ZnZmqfwQE',
    appId: '1:391352734113:web:ddeae1f472519487257be0',
    messagingSenderId: '391352734113',
    projectId: 'eqlert-11976',
    authDomain: 'eqlert-11976.firebaseapp.com',
    storageBucket: 'eqlert-11976.appspot.com',
    measurementId: 'G-3YEEG3N8SV',
  );

}